/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'createdAt' : Time,
  'text' : string,
  'author' : Principal,
}
export interface CommentInput { 'text' : string }
export type ExternalBlob = Uint8Array;
export type MediaType = { 'video' : null } |
  { 'short' : null };
export interface PublicLiveSession {
  'startTime' : Time,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'streamer' : Principal,
}
export interface PublicMediaMeta {
  'title' : string,
  'createdAt' : Time,
  'durationSeconds' : bigint,
  'mediaData' : ExternalBlob,
  'mediaType' : MediaType,
}
export type Time = bigint;
export type UploadError = { 'storageFailure' : null } |
  { 'durationExceeded' : null } |
  { 'shortIsTooShort' : null };
export type UploadResult = { 'error' : UploadError } |
  { 'success' : PublicMediaMeta };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createComment' : ActorMethod<[string, CommentInput], undefined>,
  'endLiveSession' : ActorMethod<[string], undefined>,
  'getAllActiveLiveSessions' : ActorMethod<[], Array<PublicLiveSession>>,
  'getAllShorts' : ActorMethod<[], Array<PublicMediaMeta>>,
  'getAllVideos' : ActorMethod<[], Array<PublicMediaMeta>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getLiveSession' : ActorMethod<[string], PublicLiveSession>,
  'getMediaByTitle' : ActorMethod<[string], PublicMediaMeta>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startLiveSession' : ActorMethod<[string, string], undefined>,
  'uploadMedia' : ActorMethod<
    [string, MediaType, bigint, ExternalBlob],
    UploadResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];